---

argument_specs:
  main:
    short_description: Deploys desktop tunings
    description:
      - >-
        Tasks for desktop configuration.
        Install C(ohmyzsh), setup required services
        and adjust user gropus.

    author:
      - charlesrocket

    options:
      desktop_ohmyzsh:
        description: Install C(ohmyzsh).
        type: bool
        default: false

      desktop_notifications_service:
        description: Define Freedesktop notifications service.
        type: str

      desktop_usermount:
        description: Allow users to mount.
        type: bool
        default: true

      desktop_sndiod:
        description: Enable C(sndiod).
        type: bool
        default: true

      desktop_cuse:
        description: Enable C(cuse).
        type: bool
        default: true

      desktop_acpi:
        description: Enable ACPI driver.
        type: bool
        default: false

      desktop_dsbmd:
        description: Enable DSBMD.
        type: bool
        default: true

      desktop_seatd:
        description: Enable C(seatd).
        type: bool
        default: true

      desktop_dbus:
        description: Enable D-BUS.
        type: bool
        default: true

      desktop_kde:
        description: Install KDE.
        type: bool
        default: false

      desktop_gnome:
        description: Install GNOME.
        type: bool
        default: false

      desktop_hyprland:
        description: Install Hyprland.
        type: bool
        default: false

      desktop_sddm:
        description: Install SDDM.
        type: bool
        default: false

      desktop_gdm:
        description: Install GDM.
        type: bool
        default: false
