---

- name: Converge
  hosts: all

  tasks:
    - name: Include server variables
      ansible.builtin.include_vars:
        file: ../../profiles/charlesrocket/server.yml

- name: Include server playbook
  ansible.builtin.import_playbook: charlesrocket.freebsd.server
