---

documentation:
  - changed-files:
      - any-glob-to-any-file: ['README.md', 'docs/**/*']

build:
  - changed-files:
      - any-glob-to-any-file: ['requirements-dev.txt', 'galaxy.yml']

playbook:
  - changed-files:
      - any-glob-to-any-file: 'playbooks/*'

role:
  - changed-files:
      - any-glob-to-any-file: 'roles/*'

plugin:
  - changed-files:
      - any-glob-to-any-file: 'plugins/*'

test:
  - changed-files:
      - any-glob-to-any-file: ['molecule/**/*', 'tests/**/*']

ops:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

feature:
  - head-branch: ['^feature', 'feature']
