task:
  name: Playbook test

  freebsd_instance:
    image_family: freebsd-13-0

  install_script: pkg install -y sudo git py38-ansible

  clone_script: git clone -b ${CIRRUS_BRANCH} https://github.com/charlesrocket/freebsd-station /tmp/freebsd-station

  script:
    - echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /usr/local/etc/sudoers
    - pw useradd chuck -m -G wheel
    - chown -R chuck:chuck /tmp/freebsd-station
    - su -l chuck -c 'cd /tmp/freebsd-station && ansible-galaxy install -r requirements.yml && ansible-playbook main.yml'
