task:
  name: Playbook test
  timeout_in: 120m

  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    image: family/freebsd-13-1
    platform: freebsd
    disk: 100

  install_script: pkg install -y doas git py39-ansible

  clone_script: |
    git clone -b ${CIRRUS_BRANCH} https://github.com/charlesrocket/freebsd-station /tmp/freebsd-station
    cp /tmp/freebsd-station/test/config.yml /tmp/freebsd-station/config.yml

  script: |
    echo "permit nopass keepenv chuck" > /usr/local/etc/doas.conf
    pw useradd chuck -m -G wheel
    chown -R chuck:chuck /tmp/freebsd-station
    su -l chuck -c 'cd /tmp/freebsd-station && test/idempotence_test.sh'

  test_script: |
    lynis audit system --profile /usr/local/etc/lynis/desktop.prf
