#!/bin/sh

set -eu

if ! command -v doas >/dev/null 2>&1; then
	>&2 echo "This script requires 'doas' binary to be installed"
	exit 1
fi

if [ "$(id -u)" -eq "0" ]; then
	>&2 echo "This script must be run as normal user"
	exit 1
fi

doas pkg install -y git py39-ansible

git clone https://github.com/charlesrocket/freebsd-station && cd freebsd-station

ansible-galaxy install -r requirements.yml
ansible-playbook main. yml
