#!/bin/sh

set -eu

if ! command -v sudo >/dev/null 2>&1; then
	>&2 echo "This script requires 'sudo' binary to be installed"
	exit 1
fi

if [ "$(id -u)" -eq "0" ]; then
	>&2 echo "This script must be run as normal user (WHEEL member)"
	exit 1
fi

sudo pkg install -y git py37-ansible

git clone https://github.com/charlesrocket/freebsd-playbook && cd freebsd-playbook

ansible-galaxy collection install community.general
ansible-playbook main.yml
