---
# Settings
timezone: "America/Los_Angeles"
github: charlesrocket

# Dotfiles
dotfiles_repo: "https://github.com/charlesrocket/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_force: true
dotfiles_repo_local_destination: "~/git/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .config/Kvantum/kvantum.kvconfig
  - .config/dunst/dunstrc
  - .config/gtk-3.0/settings.ini
  - .config/mc/ini
  - .config/qmk/qmk.ini
  - .config/qt5ct/qt5ct.conf
  - .config/sway/config
  - .config/transmission/settings.json
  - .config/waybar/config
  - .config/waybar/style.css
  - .config/waybar/scripts/net-if.sh
  - .config/waybar/scripts/power.sh
  - .config/wlogout/layout
  - .config/wlogout/style.css
  - .doom.d/config.el
  - .doom.d/init.el
  - .doom.d/packages.el
  - .alacritty.yml
  - .gitconfig
  - .shrc
  - .zshrc

# Configuration
asus: true
qmk: true
virtualbox: true

make_config:
  - "DEVELOPER=yes"

# Keep packages up to date
upgrade_packages: false

# Manage src/ports/doc with git
git_ports: false
git_src: false
git_doc: false

# Packages
pkgng_packages:
  - apl385
  - adwaita-icon-theme
  - adwaita-qt5
  - alacritty
  - arduino-core
  - base64
  - bash
  - bzip2
  - caja
  - chkrootkit
  - clamav
  - claws-mail
  - claws-mail-pgp
  - cmake
  - crystal
  - curl
  - cxxmatrix
  - devcpu-data
  - diffutils
  - direnv
  - dmenu
  - dmenu-wayland
  - drm-kmod
  - droid-fonts-ttf
  - dsbmc-cli
  - dsbmd
  - dunst
  - editorconfig-core-c
  - emacs
  - fdupes
  - fd-find
  - ffuf
  - figlet
  - firefox-esr
  - font-awesome
  - fzf
  - gawk
  - gcc
  - gedit
  - git
  - gitg
  - glslang
  - gmake
  - gnome-icon-theme
  - gnome-icon-theme-extras
  - gnuls
  - gnupg
  - gobuster
  - grim
  - gzip
  - hashcat
  - hs-ShellCheck
  - htop
  - httping
  - hwstat
  - iftop
  - imv
  - jq
  - Kvantum-qt5
  - less
  - llvm
  - lolcat
  - lynis
  - lynx
  - masscan
  - material-icons-ttf
  - mc
  - meson
  - mp3blaster
  - mpv
  - netcat
  - nikto
  - ninja
  - nmap
# - openssl
  - plex-ttf
  - pv
  - pwgen
  - py38-isort
  - py38-nose
  - py38-pipenv
  - python3
  - qt5-style-plugins
  - qt5ct
  - rbenv
  - ripgrep
  - rkhunter
  - rust
  - scdoc
  - seatd
  - shards
  - sudo
  - sway
  - swayidle
  - swaylock
  - tig
  - tmux
  - transmission
  - uarduno
  - unibilium
  - unzip
  - vagrant
  - virtualbox-ose
  - waybar
  - wget
  - whois
  - wireguard
  - wlogout
  - zmap
  - zsh
