---
locale: "en_US.UTF-8"
timezone: "America/Los_Angeles"

configure_asus: True
configure_virtualbox: True

upgrade_packages: False

pkgng_packages:
  - apl385
  - adwaita-icon-theme
  - adwaita-qt5
  - alacritty
  - arduino-core
  - bzip2
  - caja
  - chkrootkit
  - clamav
  - claws-mail
  - cmake
  - conky
  - crystal
  - curl
  - cursor-dmz-theme
  - cxxmatrix
  - devcpu-data
  - diffutils
  - direnv
  - dmenu
  - dmenu-wayland
  - drm-kmod
  - droid-fonts-ttf
  - dsbmc-cli
  - dsbmd
  - dunst
  - fdupes
  - ffuf
  - figlet
  - firefox
  - font-awesome
  - fusefs-exfat
  - fzf
  - gawk
  - gcc
  - git
  - gnome-icon-theme
  - gnome-icon-theme-extras
  - gnupg
  - gobuster
  - grim
  - gtk-arc-themes
  - gzip
  - hashcat
  - htop
  - httping
  - hwstat
  - iftop
  - imv
  - jq
  - kate
  - Kvantum-qt5
  - less
  - links
  - llvm
  - lolcat
  - lynis
  - masscan
  - mc
  - meson
  - mp3blaster
  - mpv
  - netcat
  - nikto
  - ninja
  - nmap
  - openssl
  - p7zip
  - pavucontrol
  - plex-ttf
  - pv
  - pwgen
  - qt5-style-plugins
  - qt5ct
  - rkhunter
  - rust
  - scdoc
  - seatd
  - shards
  - sudo
  - sway
  - swayidle
  - swaylock
  - tmux
  - tig
  - uarduno
  - unibilium
  - unzip
  - vagrant
  - virtualbox-ose
  - waybar
  - wget
  - whois
  - wireguard
  - zmap
  - zsh
