---
# Dotfiles
dotfiles_repo: "https://github.com/charlesrocket/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_force: true
dotfiles_repo_local_destination: "~/src/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .config/Kvantum/kvantum.kvconfig
  - .config/btop/btop.conf
  - .config/doom/config.el
  - .config/doom/init.el
  - .config/doom/packages.el
  - .config/dunst/dunstrc
  - .config/gtk-3.0/settings.ini
  - .config/hypr/hyprland.conf
  - .config/hypr/scripts/lowbatt.sh
  - .config/mc/ini
  - .config/qmk/qmk.ini
  - .config/qt5ct/qt5ct.conf
  - .config/tofi/config
  - .config/transmission/settings.json
  - .config/wlogout/layout
  - .config/wlogout/style.css
  - .alacritty.yml
  - .gitconfig
  - .shrc
  - .zshrc
  - bin/hyprstart

# Git
git_repo_destination: "~/src/git"
git_helper_directory: "~/bin"
git_repo_shallow: true
git_netrc_helper: true

# Configuration
asus: true
amd: false
bastille: true
doomemacs: true
intel: true
microcode_update: true
qmk: true
virtualbox: true
wifi: false

timezone: "America/Los_Angeles"
github: charlesrocket

make_config:
  - "DEVELOPER=yes"
  - "MAKE_JOBS_NUMBER?=16"

doas_config:
  - "permit nopass keepenv {{ ansible_user_id }}"

# Keep packages up to date
upgrade_packages: true

# Manage src/ports/doc with git
git_ports: false
git_src: false
git_doc: false

# Packages
pkgng_packages:
  - apl385
  - adwaita-icon-theme
  - adwaita-qt5
  - alacritty
  - arduino-core
  - base64
  - bash
  - btop
  - bzip2
  - caja
  - chkrootkit
  - clamav
  - claws-mail
  - claws-mail-pgp
  - cmake
  - crystal
  - curl
  - cxxmatrix
  - devcpu-data
  - diffutils
  - direnv
  - doas
  - drm-kmod
  - droid-fonts-ttf
  - dsbmc-cli
  - dsbmd
  - dunst
  - editorconfig-core-c
  - en-aspell
  - epdfview
  - eww-wayland
  - exfat-utils
  - fd-find
  - ffuf
  - figlet
  - filezilla
  - firefox-esr
  - font-awesome
  - fusefs-exfat
  - fusefs-ext2
  - fusefs-hfsfuse
  - fusefs-lkl
  - fusefs-ntfs
  - fusefs-simple-mtpfs
  - fzf
  - gawk
  - gcc
  - gedit
  - gimp
  - gitg
  - glslang
  - gmake
  - gnome-icon-theme
  - gnome-icon-theme-extras
  - gnuls
  - gnupg
  - gnuplot
  - gobuster
  - gomuks
  - grim
  - gtk-mixer
  - gzip
  - hashcat
  - hs-darcs
  - hs-ShellCheck
  - htop
  - httping
  - hwstat
  - hyprland
  - iftop
  - imv
  - jq
  - Kvantum-qt5
  - less
  - llvm
  - lolcat
  - lynis
  - lynx
  - masscan
  - material-icons-ttf
  - mc
  - meson
  - mp3blaster
  - mpv
  - netcat
  - nikto
  - ninja
  - nmap
  - noto-emoji
  - pcsc-tools
  - pijul
  - plex-ttf
  - portfmt
  - portlint
  - pv
  - pwgen
  - python3
  - qt5-style-plugins
  - qt5ct
  - rbenv
  - ripgrep
  - rkhunter
  - rust
  - rust-analyzer
  - scdoc
  - screen
  - seatd
  - shards
  - sndio
  - swaybg
  - swayidle
  - swaylock
  - tig
  - tmux
  - tofi
  - transmission
  - tree
  - uarduno
  - unibilium
  - unzip
  - vagrant
  - vlc
  - wdisplays
  - wget
  - whois
  - wireguard
  - wlogout
  - ykpers
  - zmap
  - zsh
