---
locale: "en_US.UTF-8"
timezone: "America/Los_Angeles"

pkgng_state: present
pkgng_packages:
  - adwaita-icon-theme
  - aide
  - alacritty
  - arduino
  - arduino-core
  - arduino-mk
  - bzip2
  - caja
  - chkrootkit
  - clamav
  - cmake
  - conky
  - crystal
  - curl
  - cursor-dmz-theme
  - diffutils
  - direnv
  - dmenu
  - dmenu-wayland
  - drm-kmod
  - droid-fonts-ttf
  - dunst
  - fdupes
  - figlet
  - firefox
  - font-awesome
  - fusefs-exfat
  - fzf
  - gawk
  - gcc
  - git
  - gnome-icon-theme
  - gnome-icon-theme-extras
  - gnupg
  - grim
  - gtk-arc-themes
  - gzip
  - hashcat
  - htop
  - httping
  - iftop
  - imv
  - less
  - links
  - llvm
  - lolcat
  - lynis
  - mc
  - meson
  - mp3blaster
  - mpv
  - neofetch
  - netcat
  - nikto
  - ninja
  - nmap
  - openssl
  - p7zip
  - pv
  - pwgen
  - rkhunter
  - rust
  - scdoc
  - seatd
  - shards
  - sudo
  - sway
  - swayidle
  - swaylock
  - tmux
  - tig
  - uarduno
  - unzip
  - vagrant
  - vim-console
  - virtualbox-ose
  - wget
  - whois
  - zmap
  - zsh
