---
- name: FreeBSD Station
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Load config.yml
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: pkg
      become: true

    - role: sys
      become: true

    - role: pf
      become: true

    - role: common

    - role: charlesrocket.git

    - role: charlesrocket.dotfiles

    - role: emacs

    - role: git_ports
      when: git_ports

    - role: git_src
      when: git_src

    - role: git_doc
      when: git_doc

    - role: asus
      when: asus

    - role: amd
      when: amd

    - role: emacs
      when: doomemacs

    - role: intel
      when: intel

    - role: qmk
      when: qmk

    - role: virtualbox
      when: virtualbox
      become: true
