---
namespace: charlesrocket
name: freebsd
version: 1.18.0
readme: README.md
description: FreeBSD collection for workstations/servers
authors:
  - charlesrocket

license:
  - MIT

tags:
  - system
  - tools
  - dotfiles
  - security
  - pf
  - pkg
  - bastille
  - emacs
  - virtualbox
  - laptop
  - desktop
  - server

dependencies:
  "ansible.posix": ">=2.1.0"
  "community.general": ">=12.2.0"
  "charlesrocket.essential": ">=1.5.0"

repository: https://codeberg.org/charlesrocket/freebsd-collection
documentation: https://charlesrocket.github.io/freebsd-collection
issues: https://codeberg.org/charlesrocket/freebsd-collection/issues
build_ignore:
  - .editorconfig
  - .github
  - .gitignore
  - assets
  - molecule
  - requirements*txt
