---

namespace: charlesrocket
name: freebsd
version: 1.9.0
readme: README.md
description: FreeBSD collection for workstations/servers
authors:
  - charlesrocket

license:
  - MIT

tags:
  - system
  - tools
  - security
  - pf
  - pkg
  - bastille
  - emacs
  - virtualbox

dependencies:
  "ansible.posix": ">=1.5.4"
  "community.general": ">=8.1.0"
  "charlesrocket.essential": ">=1.3.0"

repository: https://github.com/charlesrocket/freebsd-collection
documentation: https://charlesrocket.github.io/freebsd-collection
issues: https://github.com/charlesrocket/freebsd-collection/issues
build_ignore:
  - .editorconfig
  - .github
  - .gitignore
  - assets
  - profiles
  - molecule
  - requirements*txt
