---

namespace: charlesrocket
name: freebsd
version: 1.0.1
readme: README.md
description: FreeBSD collection for workstations/servers
authors:
  - charlesrocket

license:
  - MIT

tags:
  - infrastructure
  - development
  - freebsd
  - pf
  - pkg
  - bastille
  - emacs
  - virtualbox
  - git

dependencies:
  "ansible.posix": ">=1.5.0"
  "community.general": ">=6.5.0"
  "charlesrocket.essential": ">=1.1.0"

repository: https://github.com/charlesrocket/freebsd-collection
documentation: https://charlesrocket.github.io/freebsd-collection/
issues: https://github.com/charlesrocket/freebsd-collection/issues
build_ignore:
  - .editorconfig
  - .github
  - .gitignore
  - assets
  - profiles
  - molecule
  - requirements*txt
