---

- name: Edit user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh
    groups: cups,dialer,network,operator,realtime,video,wheel
    append: true

- name: Install ohmyzsh
  ansible.builtin.shell:
    cmd: >
      sh -c "$(curl -fsSL https://raw.githubusercontent.com
      /ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"
  become: false

- name: Allow usermount
  ansible.posix.sysctl:
    name: vfs.usermount
    state: present
    value: '1'

- name: Enable sndiod
  community.general.sysrc:
    name: sndiod_enable
    value: "YES"
    state: present

- name: Enable libcuse
  community.general.sysrc:
    name: cuse_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable ACPI video driver
  community.general.sysrc:
    name: kld_list
    value: "acpi_video"
    state: value_present

- name: Enable DSBMD
  community.general.sysrc:
    name: dsbmd_enable
    value: "YES"
    state: present

- name: Enable seatd
  community.general.sysrc:
    name: seatd_enable
    value: "YES"
    state: present

- name: Enable dbus
  community.general.sysrc:
    name: dbus_enable
    value: "YES"
    state: present

- name: Enable desktop ruleset
  community.general.sysrc:
    name: devfs_system_ruleset
    state: present
    value: "desktop"

- name: Configure devices
  ansible.builtin.blockinfile:
    path: /etc/devfs.rules
    marker: "# {mark} DESKTOP BLOCK"
    block: |
      [desktop=10]
      add path 'acd*'      mode 0660 group operator
      add path 'cd*'       mode 0660 group operator
      add path 'da*'       mode 0660 group operator
      add path 'pass*'     mode 0660 group operator
      add path 'xpt*'      mode 0660 group operator
      add path 'fd*'       mode 0660 group operator
      add path 'md*'       mode 0660 group operator
      add path 'uscanner*' mode 0660 group operator
      add path 'ugen*'     mode 0660 group operator
      add path 'usb/*'     mode 0660 group operator
      add path 'video*'    mode 0660 group operator
      add path 'cuse*'     mode 0660 group operator
      add path 'ttyU*'     mode 0660 group operator
      add path 'dri/*'     mode 0666 group video
      add path 'drm/*'     mode 0666 group video
      add path 'lpt*'      mode 0660 group cups
      add path 'ulpt*'     mode 0660 group cups
      add path 'unlpt*'    mode 0660 group cups
    mode: '0644'
    owner: root
    create: true
