---

- name: Add video group
  ansible.builtin.user:
    name: "{{ ansible_user | default(ansible_user_id) }}"
    groups: video
    append: true

- name: Install Bibata cursor
  become: false
  block:
    - name: Create cursor directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/share/icons"
        state: directory
        owner: "{{ ansible_user | default(ansible_user_id) }}"
        group: "{{ ansible_user | default(ansible_user_id) }}"
        mode: '0700'

    - name: Download Bibata Original (Classic) cursor theme
      ansible.builtin.get_url:
        url: "https://github.com/ful1e5/Bibata_Cursor/releases/download/\
          v2.0.7/Bibata-Original-Classic.tar.xz"
        dest: /tmp/Bibata-Original-Classic.tar.xz
        mode: '0700'
        checksum:
          sha256:158b2e7e1b7f6d0eec1af80a93172960dd083b652fef7589575ee984673cc468
      notify: Deploy Bibata Original Classic

- name: Install ohmyzsh
  ansible.builtin.shell:
    cmd: >-
      sh -c
      "$(curl -fsSL
      https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      "" --unattended
  args:
    creates: "/home/{{ ansible_user | default(ansible_user_id) }}/.oh-my-zsh"
  become: false
  when: desktop_ohmyzsh

- name: Ensures D-Bus services directory exists
  become: false
  when: desktop_notifications_service is defined
  tags: dbus
  ansible.builtin.file:
    path: "~/.local/share/dbus-1/services"
    state: directory
    mode: '0755'

- name: Add XDG notifications service
  become: false
  when: desktop_notifications_service is defined
  tags: dbus
  ansible.builtin.copy:
    dest: "~/.local/share/dbus-1/services/org.freedesktop.Notifications.service"
    mode: '0644'
    content: |
      [D-BUS Service]
      Name=org.freedesktop.Notifications
      Exec=/usr/local/bin/{{ desktop_notifications_service }}

- name: Install Hyprland
  when: desktop_hyprland
  tags: hyprland
  community.general.pkgng:
    state: present
    cached: false
    name:
      - hyprland
      - hyprland-qt-support
      - hyprqt6engine
      - hyprland-protocols
      - hyprutils
      - hyprpaper
      - hyprlock
      - hyprcursor
      - hyprpolkitagent
      - xdg-desktop-portal-hyprland

- name: Install webcamd
  when: desktop_webcamd is defined
  tags: webcam
  community.general.pkgng:
    state: present
    name: webcamd
    cached: false

- name: Install CUPS
  when: desktop_cups is defined
  tags: printer
  community.general.pkgng:
    state: present
    name: cups
    cached: false

- name: Install KDE
  when: desktop_kde
  tags: kde
  community.general.pkgng:
    state: present
    name: kde
    cached: false

- name: Install GNOME
  when: desktop_gnome
  tags: gnome
  community.general.pkgng:
    state: present
    name: gnome
    cached: false

- name: Install SDDM
  when: desktop_sddm
  tags: sddm
  community.general.pkgng:
    state: present
    name: sddm
    cached: false

- name: Install GDM
  when: desktop_gdm
  tags: gdm
  community.general.pkgng:
    state: present
    name: gdm
    cached: false

- name: "SDDM | {{ desktop_sddm | ternary('enable', 'disable') }}"
  tags: sddm
  community.general.sysrc:
    name: sddm_enable
    state: present
    value: "{{ desktop_sddm | ternary('YES', 'NO') }}"

- name: "GDM | {{ desktop_gdm | ternary('enable', 'disable') }}"
  tags: gdm
  community.general.sysrc:
    name: gdm_enable
    state: present
    value: "{{ desktop_gdm | ternary('YES', 'NO') }}"

- name: "Webcam | {{ desktop_webcamd | ternary('enable', 'disable') }}"
  when: desktop_webcamd is defined
  tags: webcam
  community.general.sysrc:
    name: webcamd_enable
    state: present
    value: "{{ desktop_webcamd | ternary('YES', 'NO') }}"

- name: "CUPS | {{ desktop_cups | ternary('enable', 'disable') }}"
  when: desktop_cups is defined
  tags: printer
  community.general.sysrc:
    name: cupsd_enable
    state: present
    value: "{{ desktop_cups | ternary('YES', 'NO') }}"

- name: "Usermount | {{ desktop_usermount | ternary('enable', 'disable') }}"
  ansible.posix.sysctl:
    name: vfs.usermount
    state: present
    value: "{{ desktop_usermount | ternary('1', '0') }}"

- name: "SNDIOD | {{ desktop_sndiod | ternary('enable', 'disable') }}"
  community.general.sysrc:
    name: sndiod_enable
    state: present
    value: "{{ desktop_sndiod | ternary('YES', 'NO') }}"

- name: "CUSE | {{ desktop_cuse | ternary('enable', 'disable cuse') }}"
  community.general.sysrc:
    name: cuse_load
    state: present
    value: "{{ desktop_cuse | ternary('YES', 'NO') }}"
    path: /boot/loader.conf

- name: "ACPI video driver | {{ desktop_acpi | ternary('enable', 'disable') }}"
  community.general.sysrc:
    name: kld_list
    state: "{{ desktop_acpi | ternary('value_present', 'value_absent') }}"
    value: "acpi_video"

- name: "DSBMD | {{ desktop_dsbmd | ternary('enable', 'disable') }}"
  community.general.sysrc:
    name: dsbmd_enable
    state: present
    value: "{{ desktop_dsbmd | ternary('YES', 'NO') }}"

- name: "SEATD | {{ desktop_seatd | ternary('enable', 'disable') }}"
  community.general.sysrc:
    name: seatd_enable
    state: present
    value: "{{ desktop_seatd | ternary('YES', 'NO') }}"

- name: "D-Bus | {{ desktop_dbus | ternary('enable', 'disable') }}"
  tags: dbus
  community.general.sysrc:
    name: dbus_enable
    state: present
    value: "{{ desktop_dbus | ternary('YES', 'NO') }}"

- name: Configure devices
  ansible.builtin.blockinfile:
    path: /etc/devfs.rules
    marker: "# {mark} DESKTOP BLOCK"
    block: |
      [desktop=10]
      add path 'acd*'      mode 0660 group operator
      add path 'cd*'       mode 0660 group operator
      add path 'da*'       mode 0660 group operator
      add path 'pass*'     mode 0660 group operator
      add path 'xpt*'      mode 0660 group operator
      add path 'fd*'       mode 0660 group operator
      add path 'md*'       mode 0660 group operator
      add path 'uscanner*' mode 0660 group operator
      add path 'ugen*'     mode 0660 group operator
      add path 'usb/*'     mode 0660 group operator
      add path 'video*'    mode 0660 group operator
      add path 'cuse*'     mode 0660 group operator
      add path 'ttyU*'     mode 0660 group operator
      add path 'dri/*'     mode 0666 group video
      add path 'drm/*'     mode 0666 group video
      add path 'lpt*'      mode 0660 group cups
      add path 'ulpt*'     mode 0660 group cups
      add path 'unlpt*'    mode 0660 group cups
    mode: '0644'
    owner: root
    create: true

- name: Enable desktop ruleset
  community.general.sysrc:
    name: devfs_system_ruleset
    state: present
    value: "desktop"
