---

- name: Ensure video group is present
  ansible.builtin.user:
    name: "{{ ansible_user | default(ansible_user_id) }}"
    groups: video
    append: true

- name: Install ohmyzsh
  ansible.builtin.shell:
    cmd: >-
      sh -c
      "$(curl -fsSL
      https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      "" --unattended
  args:
    creates: "/home/{{ ansible_user | default(ansible_user_id) }}/.oh-my-zsh"
  become: false
  when:
    - "'zsh' in ansible_facts.packages"

- name: "Usermount | {{ usermount | ternary('enable', 'disable') }}"
  ansible.posix.sysctl:
    name: vfs.usermount
    state: present
    value: "{{ usermount | ternary('1', '0') }}"

- name: "{{ sndiod | ternary('Enable sndio', 'Disable sndio') }}"
  community.general.sysrc:
    name: sndiod_enable
    state: present
    value: "{{ sndiod | ternary('YES', 'NO') }}"

- name: "{{ cuse | ternary('Enable cuse', 'Disable cuse') }}"
  community.general.sysrc:
    name: cuse_load
    state: present
    value: "{{ cuse | ternary('YES', 'NO') }}"
    path: /boot/loader.conf

- name: "ACPI video driver | {{ acpi | ternary('enable', 'disable') }}"
  community.general.sysrc:
    name: kld_list
    state: "{{ acpi | ternary('value_present', 'value_absent') }}"
    value: "acpi_video"

- name: "{{ dsbmd | ternary('Enable DSBMD', 'Disable DSBMD') }}"
  community.general.sysrc:
    name: dsbmd_enable
    state: present
    value: "{{ dsbmd | ternary('YES', 'NO') }}"

- name: "{{ seatd | ternary('Enable seatd', 'Disable seatd') }}"
  community.general.sysrc:
    name: seatd_enable
    state: present
    value: "{{ seatd | ternary('YES', 'NO') }}"

- name: "{{ dbus | ternary('Enable dbus', 'Disable dbus') }}"
  community.general.sysrc:
    name: dbus_enable
    state: present
    value: "{{ dbus | ternary('YES', 'NO') }}"

- name: Enable desktop ruleset
  community.general.sysrc:
    name: devfs_system_ruleset
    state: present
    value: "desktop"

- name: Configure devices
  ansible.builtin.blockinfile:
    path: /etc/devfs.rules
    marker: "# {mark} DESKTOP BLOCK"
    block: |
      [desktop=10]
      add path 'acd*'      mode 0660 group operator
      add path 'cd*'       mode 0660 group operator
      add path 'da*'       mode 0660 group operator
      add path 'pass*'     mode 0660 group operator
      add path 'xpt*'      mode 0660 group operator
      add path 'fd*'       mode 0660 group operator
      add path 'md*'       mode 0660 group operator
      add path 'uscanner*' mode 0660 group operator
      add path 'ugen*'     mode 0660 group operator
      add path 'usb/*'     mode 0660 group operator
      add path 'video*'    mode 0660 group operator
      add path 'cuse*'     mode 0660 group operator
      add path 'ttyU*'     mode 0660 group operator
      add path 'dri/*'     mode 0666 group video
      add path 'drm/*'     mode 0666 group video
      add path 'lpt*'      mode 0660 group cups
      add path 'ulpt*'     mode 0660 group cups
      add path 'unlpt*'    mode 0660 group cups
    mode: '0644'
    owner: root
    create: true
