---

- name:
    "Process accounting | {{ proc_accounting | ternary('enable', 'disable') }}"
  community.general.sysrc:
    name: accounting_enable
    state: present
    value: "{{ proc_accounting | ternary('YES', 'NO') }}"
