---

galaxy_info:
  author: charlesrocket
  description: Add USB tethering
  role_name: tethering
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - apple
