---
- name: Ensure wpa_supplicant is installed
  community.general.pkgng:
    state: present
    name: wpa_supplicant
    autoremove: true
    cached: false
  become: true

- name: Enable Atheros
  community.general.sysrc:
    name: if_ath_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable iwm driver
  community.general.sysrc:
    name: if_iwn_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  when: intel

- name: Enable WEP
  community.general.sysrc:
    name: wlan_wep_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable CCMP
  community.general.sysrc:
    name: wlan_ccmp_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable TKIP
  community.general.sysrc:
    name: wlan_tkip_load
    state: present
    value: "YES"
    path: /boot/loader.conf
