---

- name: Edit user
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh
    groups: dialer,video
    append: yes
  become: True

- name: Suspend on lid close
  ansible.posix.sysctl:
    name: hw.acpi.lid_switch_state
    state: present
    value: 'S3'
  become: True

- name: Hide UIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_uids
    state: present
    value: '0'
  become: True

- name: Clear /tmp
  community.general.sysrc:
    name: clear_tmp_enable
    value: "YES"
    state: present
  become: True

- name: Enable ntpd
  community.general.sysrc:
    name: ntpd_enable
    value: "YES"
    state: present
  become: True

- name: Tune ntpd
  community.general.sysrc:
    name: ntpd_flags
    value: "-g"
    state: present
  become: True

- name: Disable sendmail
  community.general.sysrc:
    name: sendmail_enable
    value: "NONE"
    state: present
  become: True

- name: Set autoboot delay
  community.general.sysrc:
    name: autoboot_delay
    state: present
    value: "3"
    path: /boot/loader.conf
  become: True

- name: Boot in verbose mode
  community.general.sysrc:
    name: boot_verbose
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Change loader logo
  community.general.sysrc:
    name: loader_logo
    state: present
    value: "beastie"
    path: /boot/loader.conf
  become: True

- name: Enable coretemp
  community.general.sysrc:
    name: coretemp_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Enable cpuctl
  community.general.sysrc:
    name: cpuctl_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Enable AES-NI
  community.general.sysrc:
    name: aesni_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Enable H-TCP
  community.general.sysrc:
    name: cc_htcp_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Enable UHD driver
  community.general.sysrc:
    name: kld_list
    value: "i915kms"
    state: value_present
  become: True

- name: Enable ACPI video driver
  community.general.sysrc:
    name: kld_list
    value: "acpi_video"
    state: value_present
  become: True

- name: Enable seatd
  community.general.sysrc:
    name: seatd_enable
    value: "YES"
    state: present
  become: True

- name: Don't pong
  community.general.sysrc:
    name: icmp_bmcastecho
    state: present
    value: "NO"
  become: True

- name: Load DHCP client in the background
  community.general.sysrc:
    name: background_dhclient
    value: "YES"
    state: present
  become: True

- name: Enable IPv6
  community.general.sysrc:
    name: rtsold_enable
    value: "YES"
    state: present
  become: True

- name: Tune IPv6
  community.general.sysrc:
    name: rtsold_flags
    value: "-aF"
    state: present
  become: True

- name: Enable powerd
  community.general.sysrc:
    name: powerd_enable
    value: "YES"
    state: present
  become: True

- name: Tune powerd
  community.general.sysrc:
    name: powerd_flags
    value: "-a hiadaptive -b adaptive"
    state: present
  become: True

- name: Tune syslogd
  community.general.sysrc:
    name: syslogd_flags
    value: "-ss"
    state: present
  become: True

- name: Enable WiFi power saving
  community.general.sysrc:
    name: ifconfig_wlan0
    value: "WPA DHCP powersave"
    state: present
  become: True

- name: Tune C-states - performance
  community.general.sysrc:
    name: performance_cx_lowest
    value: "Cmax"
    state: present
  become: True

- name: Tune C-states - economy
  community.general.sysrc:
    name: economy_cx_lowest
    value: "Cmax"
    state: present
  become: True

- name: Disable kernel crash dumps
  community.general.sysrc:
    name: dumpdev
    state: present
    value: "NO"
  become: True

- name: Upgrade installed packages
  community.general.pkgng:
    name: "*"
    state: latest
  become: True
  when: upgrade_packages

- name: Copy MOTD
  copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0755
  become: True

- name: Install MOTD
  cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: True

- name: Edit sh prompt
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.shrc
    line: 'export PS1="\u@\H x: "'
    state: present

- name: Install ohmyzsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"

- name: Ensure sway/scripts directory exists
  file:
    path: ~/.config/sway/scripts
    state: directory
    mode: 0744

- name: Ensure GTK directory exists
  file:
    path: ~/.config/gtk-3.0
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0744

- name: Ensure mc directory exists
  file:
    path: ~/.config/mc
    state: directory
    mode: 0744

- name: Copy conky config file
  copy:
    src: conkyrc
    dest: ~/.conkyrc
    owner: "{{ ansible_user_id }}"
    mode: 0744
    force: yes

- name: Set interfaces (IPv4) in conkyrc
  replace:
    path: ~/.conkyrc
    regexp: 'wlan0'
    replace: "{{ ansible_facts['default_ipv4']['interface'] }}"
  when: ansible_default_ipv4 and not ansible_default_ipv6

- name: Set interfaces (IPv6) in conkyrc
  replace:
    path: ~/.conkyrc
    regexp: 'wlan0'
    replace: "{{ ansible_facts['default_ipv6']['interface'] }}"
  when: ansible_default_ipv6 and not ansible_default_ipv4

- name: Copy sway config file
  copy:
    src: swayconfig
    dest: ~/.config/sway/config
    owner: "{{ ansible_user_id }}"
    mode: 0744
    force: yes

- name: Copy sway-bar script
  copy:
    src: swaybar.sh
    dest: ~/.config/sway/swaybar.sh
    owner: "{{ ansible_user_id }}"
    mode: 0744

- name: Copy gsettings script
  copy:
    src: import-gsettings
    dest: ~/.config/sway/scripts/import-gsettings
    owner: "{{ ansible_user_id }}"
    mode: 0744

- name: Copy GTK settings
  copy:
    src: settings.ini
    dest: ~/.config/gtk-3.0/settings.ini
    owner: "{{ ansible_user_id }}"
    mode: 0644
    force: yes

- name: Copy mc config file
  copy:
    src: mcini
    dest: ~/.config/mc/ini
    owner: "{{ ansible_user_id }}"
    mode: 0744
    force: yes

- name: Copy zsh config
  copy:
    src: zshrc
    dest: ~/.zshrc
    owner: "{{ ansible_user_id }}"
    mode: 0644
    force: yes

- name: Copy alacritty config
  copy:
    src: alacritty.yml
    dest: ~/.alacritty.yml
    owner: "{{ ansible_user_id }}"
    mode: 0644
    force: yes
