---

- name: Edit user
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh
    groups: dialer,video
    append: yes
  become: True

- name: Enable UHD driver
  community.general.sysrc:
    name: kld_list
    value: "i915kms"
    state: present
  become: True

- name: Enable ACPI video driver
  community.general.sysrc:
    name: kld_list
    value: "acpi_video"
    state: value_present
  become: True

- name: Enable seatd
  community.general.sysrc:
    name: seatd_enable
    value: "YES"
    state: present
  become: True

- name: Upgrade installed packages
  pkgng:
    name: "*"
    state: latest
  become: True

- name: Copy MOTD
  copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0755
  become: True

- name: Install MOTD
  cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: True

- name: Edit sh prompt
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.shrc
    line: 'export PS1="\u@\H x: "'
    state: present

- name: Install ohmyzsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"

- name: Ensure sway/scripts directory exists
  file:
    path: ~/.config/sway/scripts
    state: directory
    mode: '0744'

- name: Ensure GTK directory exists
  file:
    path: ~/.config/gtk-3.0
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: '0744'

- name: Copy conky config file
  copy:
    src: conkyrc
    dest: ~/.conkyrc
    owner: "{{ ansible_user_id }}"
    mode: '0744'
    force: yes

- name: Copy sway config file
  copy:
    src: swayconfig
    dest: ~/.config/sway/config
    owner: "{{ ansible_user_id }}"
    mode: '0744'
    force: yes

- name: Copy sway-bar script
  copy:
    src: swaybar.sh
    dest: ~/.config/sway/swaybar.sh
    owner: "{{ ansible_user_id }}"
    mode: '0744'

- name: Copy gsettings script
  copy:
    src: import-gsettings
    dest: ~/.config/sway/scripts/import-gsettings
    owner: "{{ ansible_user_id }}"
    mode: '0744'

- name: Copy GTK settings
  copy:
    src: settings.ini
    dest: ~/.config/gtk-3.0/settings.ini
    owner: "{{ ansible_user_id }}"
    mode: '0644'
    force: yes

- name: Copy zsh config
  copy:
    src: zshrc
    dest: ~/.zshrc
    owner: "{{ ansible_user_id }}"
    mode: 0644
    force: yes

- name: Copy alacritty config
  copy:
    src: alacritty.yml
    dest: ~/.alacritty.yml
    owner: "{{ ansible_user_id }}"
    mode: 0644
    force: yes
