---
- name: Clone Doom Emacs
  ansible.builtin.git:
    repo: 'https://github.com/hlissner/doom-emacs'
    dest: ~/.emacs.d
    version: master
  register: doom_emacs

handlers:
    - name: Sync Doom Emacs
      ansible.builtin.command: ~/.emacs.d/bin/doom sync
      when: doom_emacs is changed
