---
- name: Clone git repository
  ansible.builtin.git:
    repo: https://github.com/git/git.git
    dest: ~/git/git
    version: master
  notify:
    - Build git-credential-netrc
    - Deploy git-credential-netrc
