---
- name: Clone git repository
  ansible.builtin.git:
    repo: https://github.com/git/git.git
    dest: ~/git/git
    version: master

- name: Build git-credential-netrc
  ansible.builtin.command: gmake
  args:
    chdir: ~/git/git/contrib/credential/netrc/
    creates: ~/git/git/contrib/credential/netrc/git-credential-netrc

- name: Deploy git-credential-netrc
  ansible.builtin.copy:
    src: ~/git/git/contrib/credential/netrc/git-credential-netrc
    dest: ~/bin/git-credential-netrc
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
