---
- name: Add user groups
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: vboxusers,operator
    append: true
  become: true

- name: Enable virtualbox driver
  community.general.sysrc:
    name: vboxdrv_load
    value: "YES"
    state: present
    path: /boot/loader.conf
  become: true

- name: Enable vboxnet driver
  community.general.sysrc:
    name: vboxnet_enable
    state: present
    value: "YES"
  become: true

- name: Add USB permissions
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    line: 'devfs_system_ruleset="system"'
    state: present
  become: true

- name: Edit devfs.rules
  ansible.builtin.blockinfile:
    path: /etc/devfs.rules
    block: |
      [system=10]
      add path 'usb/*' mode 0660 group operator
    mode: 0644
    owner: root
    create: true
  become: true
