---
- name: Add user groups
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: vboxusers,operator
    append: true
  become: true

- name: Enable virtualbox driver
  community.general.sysrc:
    name: vboxdrv_load
    value: "YES"
    state: present
    path: /boot/loader.conf
  become: true

- name: Enable vboxnet driver
  community.general.sysrc:
    name: vboxnet_enable
    state: present
    value: "YES"
  become: true

- name: Add USB permissions
  community.general.sysrc:
    name: devfs_system_ruleset
    state: present
    value: "system"
  become: true

- name: Add virtualbox ruleset
  ansible.builtin.blockinfile:
    path: /etc/devfs.rules
    marker: "# {mark} VIRTUALBOX BLOCK"
    block: |
      [system=10]
      add path 'usb/*' mode 0660 group operator
    mode: 0644
    owner: root
    create: true
  become: true
