---

- name: Ensure sway/scripts directory exists
  file:
    path: ~/.config/sway/scripts
    state: directory
    mode: 0744

- name: Ensure waybar directory exists
  file:
    path: ~/.config/waybar
    state: directory
    mode: 0744

- name: Ensure GTK directory exists
  file:
    path: ~/.config/gtk-3.0
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0744

- name: Copy sway config file
  copy:
    src: swayconfig
    dest: ~/.config/sway/config
    owner: "{{ ansible_user_id }}"
    mode: 0744
    force: yes

- name: Copy waybar config file
  copy:
    src: waybarconfig
    dest: ~/.config/waybar/config
    owner: "{{ ansible_user_id }}"
    mode: 0744

- name: Copy waybar css file
  copy:
    src: waybar.css
    dest: ~/.config/waybar/style.css
    owner: "{{ ansible_user_id }}"
    mode: 0744

- name: Copy gsettings script
  copy:
    src: import-gsettings
    dest: ~/.config/sway/scripts/import-gsettings
    owner: "{{ ansible_user_id }}"
    mode: 0744

- name: Copy GTK settings
  copy:
    src: settings.ini
    dest: ~/.config/gtk-3.0/settings.ini
    owner: "{{ ansible_user_id }}"
    mode: 0644
    force: yes
