---

galaxy_info:
  author: charlesrocket
  description: Manage WireGuard
  role_name: wg
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - wireguard
