---

- name: Ensure configuration directory exists
  ansible.builtin.file:
    path: /usr/local/etc/pkg/repos
    state: directory
    owner: root
    group: wheel
    mode: '0755'

- name: Copy configuration file
  ansible.builtin.copy:
    src: /etc/pkg/FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: '0644'
    remote_src: true
    force: false

- name: Ensure packages are installed
  community.general.pkgng:
    state: present
    name: "{{ pkgng_packages }}"
    autoremove: true
    cached: false

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
    strategy: all
