---

- name: Ensure packages are installed
  community.general.pkgng:
    state: present
    name: "{{ pkgng_packages }}"
    autoremove: true
    cached: false

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
    strategy: all
