---

galaxy_info:
  author: charlesrocket
  description: Deploy Bastille
  role_name: bastille
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - bastille
