---

galaxy_info:
  author: charlesrocket
  description: Deploy VirtualBox
  role_name: virtualbox
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - virtualbox
