---

galaxy_info:
  author: charlesrocket
  description: Manage kernel security levels
  role_name: kern_sec
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - security
    - system
