---

galaxy_info:
  author: charlesrocket
  description: Manage DRM drivers
  role_name: drm
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - drm
