---

- name: Ensure pip is installed
  community.general.pkgng:
    state: present
    name: py38-pip
    autoremove: true
    cached: false
  become: true

- name: Install wheel
  ansible.builtin.pip:
    name: wheel
    state: present

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ pip_packages }}"
