---

galaxy_info:
  author: charlesrocket
  description: Deploy ClamAV
  role_name: clamav
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - antivirus
    - clamav
