---

- name: >-
    Set ports branch | {{ (pkg_latest_branch == true) |
    ternary('latest', 'quarterly') }}
  ansible.builtin.replace:
    path: /usr/local/etc/pkg/repos/FreeBSD.conf
    regexp: "{{ (pkg_latest_branch == true) | ternary('quarterly', 'latest') }}"
    replace:
      "{{ (pkg_latest_branch == true) | ternary('latest', 'quarterly') }}"
    register: pkg_branch

- name: Redownload repository catalogue
  ansible.builtin.command: pkg update -f
  register: pkg_output
  changed_when:
    - '"need to re-create database" in pkg_output.stderr'
  when: pkg_latest_branch

- name: Upgrade installed packages
  community.general.pkgng:
    name: "*"
    state: latest
    autoremove: true
    cached: false
  when: upgrade_packages or pkg_latest_branch
