---

- name: >-
    Set pkg branch to {{ pkg_branch_name }}
  ansible.builtin.replace:
    path: /usr/local/etc/pkg/repos/FreeBSD.conf
    regexp: >-
      {{ (pkg_branch_name == 'latest') | ternary('quarterly',
      'latest') }}
    replace: >-
      {{ (pkg_branch_name == 'latest') | ternary('latest', 'quarterly') }}
  notify:
    - Redownload repository catalogue
    - Upgrade installed packages
