---
- name: Use latest branch
  ansible.builtin.replace:
    path: /usr/local/etc/pkg/repos/FreeBSD.conf
    regexp: 'quarterly'
    replace: 'latest'
  register: pkg_branch
  when: latest_branch
  notify:
    - Redownload repository catalogue
    - Upgrade packages

- name: Ensure packages are upgraded to the latest version
  ansible.builtin.assert: { that: true, quiet: true }
  changed_when: true
  when: upgrade_packages
  notify:
    - Upgrade packages
