---
- name: Use latest branch
  ansible.builtin.replace:
    path: /usr/local/etc/pkg/repos/FreeBSD.conf
    regexp: 'quarterly'
    replace: 'latest'
  register: pkg_branch
  notify:
    - Redownload repository catalogue

- name: Upgrade installed packages
  ansible.builtin.assert: { that: true, quiet: true }
  changed_when: true
  when: upgrade_packages or pkg_branch is changed
  notify:
    - Upgrade packages
