---

- name: >-
    Set pkg branch to {{ pkg_branch }}
  ansible.builtin.replace:
    path: /usr/local/etc/pkg/repos/FreeBSD.conf
    regexp: "{{ (pkg_branch == 'latest') | ternary('quarterly', 'latest') }}"
    replace:
      "{{ (pkg_branch == 'latest') | ternary('latest', 'quarterly') }}"
  notify:
    - Redownload repository catalogue
    - Upgrade installed packages
