---

argument_specs:
  main:
    short_description: Adjusts system settings
    description:
      - System tunings and hardening.

    author:
      - charlesrocket

    options:
      doas_config:
        description: List of C(doas) options.
        type: list
        elements: str

      hostname:
        description: Set hostname.
        type: str

      timezone:
        description: Set timezone.
        type: str

      microcode_update:
        description: Enable microcode updates.
        type: bool
        default: false
