---

galaxy_info:
  author: charlesrocket
  description: Manage system settings
  role_name: sys
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - system
    - doas
