---

galaxy_info:
  author: charlesrocket
  description: Install and configure poudriere
  role_name: poudriere
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - poudriere
