---

- name: Ensure QMK is installed
  community.general.pkgng:
    state: present
    name: py311-qmk
    autoremove: true
    cached: false
  become: true

- name: Clone QMK userspace
  ansible.builtin.git:
    repo: "{{ qmk_userspace }}"
    dest: "{{ qmk_userspace_location }}"
  changed_when: false
