---
- name: Ensure QMK is installed
  community.general.pkgng:
    state: present
    name: sysutils/py-qmk
    autoremove: true
    cached: false
  become: true

- name: Clone QMK firmware
  ansible.builtin.git:
    repo: "https://github.com/{{ github }}/qmk_firmware"
    dest: ~/src/qmk_firmware
    version: master
  changed_when: false
