---

- name: Converge
  hosts: all

  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        file: ../../profiles/charlesrocket/station.yml

    - name: Include test variables
      ansible.builtin.include_vars:
        file: ../../profiles/test/station.yml

- name: Include station playbook
  ansible.builtin.import_playbook: charlesrocket.freebsd.station
