---
- name: Suspend on lid close
  ansible.posix.sysctl:
    name: hw.acpi.lid_switch_state
    state: present
    value: 'S3'

- name: Hide UIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_uids
    state: present
    value: '0'

- name: Allow usermount
  ansible.posix.sysctl:
    name: vfs.usermount
    state: present
    value: '1'

- name: Clear /tmp
  community.general.sysrc:
    name: clear_tmp_enable
    value: "YES"
    state: present

- name: Enable microcode updates
  community.general.sysrc:
    name: microcode_update_enable
    value: "YES"
    state: present

- name: Enable ntpd
  community.general.sysrc:
    name: ntpd_enable
    value: "YES"
    state: present

- name: Tune ntpd
  community.general.sysrc:
    name: ntpd_flags
    value: "-g"
    state: present

- name: Disable sendmail
  community.general.sysrc:
    name: sendmail_enable
    value: "NONE"
    state: present

- name: Set autoboot delay
  community.general.sysrc:
    name: autoboot_delay
    state: present
    value: "2"
    path: /boot/loader.conf

- name: Boot in verbose mode
  community.general.sysrc:
    name: boot_verbose
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Change loader logo
  community.general.sysrc:
    name: loader_logo
    state: present
    value: "beastie"
    path: /boot/loader.conf

- name: Enable coretemp
  community.general.sysrc:
    name: coretemp_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable cpuctl
  community.general.sysrc:
    name: cpuctl_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable AES-NI
  community.general.sysrc:
    name: aesni_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable H-TCP
  community.general.sysrc:
    name: cc_htcp_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable UHD driver
  community.general.sysrc:
    name: kld_list
    value: "i915kms"
    state: value_present

- name: Enable ACPI video driver
  community.general.sysrc:
    name: kld_list
    value: "acpi_video"
    state: value_present

- name: Enable DSBMD
  community.general.sysrc:
    name: dsbmd_enable
    value: "YES"
    state: present

- name: Enable seatd
  community.general.sysrc:
    name: seatd_enable
    value: "YES"
    state: present

- name: Enable dbus
  community.general.sysrc:
    name: dbus_enable
    value: "YES"
    state: present

- name: Don't pong
  community.general.sysrc:
    name: icmp_bmcastecho
    state: present
    value: "NO"

- name: Load DHCP client in the background
  community.general.sysrc:
    name: background_dhclient
    value: "YES"
    state: present

- name: Enable IPv6
  community.general.sysrc:
    name: rtsold_enable
    value: "YES"
    state: present

- name: Tune IPv6
  community.general.sysrc:
    name: rtsold_flags
    value: "-aF"
    state: present

- name: Enable powerd
  community.general.sysrc:
    name: powerd_enable
    value: "YES"
    state: present

- name: Tune powerd
  community.general.sysrc:
    name: powerd_flags
    value: "-a hiadaptive -b adaptive"
    state: present

- name: Tune syslogd
  community.general.sysrc:
    name: syslogd_flags
    value: "-ss"
    state: present

- name: Enable WiFi power saving
  community.general.sysrc:
    name: ifconfig_wlan0
    value: "WPA DHCP powersave"
    state: present

- name: Tune C-states - performance
  community.general.sysrc:
    name: performance_cx_lowest
    value: "Cmax"
    state: present

- name: Tune C-states - economy
  community.general.sysrc:
    name: economy_cx_lowest
    value: "Cmax"
    state: present

- name: Disable kernel crash dumps
  community.general.sysrc:
    name: dumpdev
    state: present
    value: "NO"
