---

- name: Set hostname
  community.general.sysrc:
    name: hostname
    value: "{{ hostname }}"
    state: present
  when: hostname is defined

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  when: timezone is defined

- name: Tune TTYs
  ansible.builtin.replace:
    path: /etc/ttys
    regexp: '(?:^|\W)secure(?:$|\W)'
    replace: ' insecure'

- name: Configure doas
  ansible.builtin.template:
    src: doas.conf.j2
    dest: /usr/local/etc/doas.conf
    owner: root
    group: wheel
    mode: '0644'

- name: Randomize PID
  ansible.posix.sysctl:
    name: kern.randompid
    state: present
    value: '1'
    reload: false

- name: Disable coredump
  ansible.posix.sysctl:
    name: kern.coredump
    state: present
    value: '0'

- name: Restrict debugging
  ansible.posix.sysctl:
    name: security.bsd.unprivileged_proc_debug
    state: present
    value: '0'

- name: Restrict message buffer
  ansible.posix.sysctl:
    name: security.bsd.unprivileged_read_msgbuf
    state: present
    value: '0'

- name: Hide processes running in jails
  ansible.posix.sysctl:
    name: security.bsd.see_jail_proc
    state: present
    value: '0'

- name: Hide GIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_gids
    state: present
    value: '0'

- name: Hide UIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_uids
    state: present
    value: '0'

- name: Clear /tmp
  community.general.sysrc:
    name: clear_tmp_enable
    value: "YES"
    state: present

- name: Enable microcode updates
  community.general.sysrc:
    name: microcode_update_enable
    value: "YES"
    state: present
  notify:
    - Update CPU firmware
  when: microcode_update

- name: Enable ntpd
  community.general.sysrc:
    name: ntpd_enable
    value: "YES"
    state: present

- name: Sync ntpd on start
  community.general.sysrc:
    name: ntpd_sync_on_start
    value: "YES"
    state: present

- name: Enable ntpd OOM protection
  community.general.sysrc:
    name: ntpd_oomprotect
    value: "YES"
    state: present

- name: Disable sendmail | incoming
  community.general.sysrc:
    name: sendmail_enable
    value: "NO"
    state: present

- name: Disable sendmail | submit
  community.general.sysrc:
    name: sendmail_submit_enable
    value: "NO"
    state: present

- name: Disable sendmail | outbound
  community.general.sysrc:
    name: sendmail_outbound_enable
    value: "NO"
    state: present

- name: Disable sendmail | msp_queue
  community.general.sysrc:
    name: sendmail_msp_queue_enable
    value: "NO"
    state: present

- name: Set autoboot delay
  community.general.sysrc:
    name: autoboot_delay
    state: present
    value: "2"
    path: /boot/loader.conf

- name: Boot in verbose mode
  community.general.sysrc:
    name: boot_verbose
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Change loader logo
  community.general.sysrc:
    name: loader_logo
    state: present
    value: "orbbw"
    path: /boot/loader.conf

- name: Enable AIO
  community.general.sysrc:
    name: aio_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable coretemp
  community.general.sysrc:
    name: coretemp_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable cpuctl
  community.general.sysrc:
    name: cpuctl_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable AES-NI
  community.general.sysrc:
    name: aesni_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable H-TCP
  community.general.sysrc:
    name: cc_htcp_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Don't pong
  community.general.sysrc:
    name: icmp_bmcastecho
    state: present
    value: "NO"

- name: Load DHCP client in the background
  community.general.sysrc:
    name: background_dhclient
    value: "YES"
    state: present

- name: Enable IPv6
  community.general.sysrc:
    name: rtsold_enable
    value: "YES"
    state: present

- name: Tune IPv6
  community.general.sysrc:
    name: rtsold_flags
    value: "-aF"
    state: present

- name: Tune syslogd
  community.general.sysrc:
    name: syslogd_flags
    value: "-ss"
    state: present

- name: Disable kernel crash dumps
  community.general.sysrc:
    name: dumpdev
    state: present
    value: "NO"

- name: Fix file permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: wheel
    mode: "{{ item.mode }}"
  loop:
    - { path: /etc/cron.d, mode: '0700' }
    - { path: /etc/crontab, mode: '0600' }
    - { path: /etc/ssh/sshd_config, mode: '0600' }
