---

- name: Set hostname
  community.general.sysrc:
    name: hostname
    value: "{{ hostname }}"
    state: present
  when: hostname is defined

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  when: timezone is defined

- name: Tune TTYs
  ansible.builtin.replace:
    path: /etc/ttys
    regexp: '(?:^|\W)secure(?:$|\W)'
    replace: ' insecure'

- name: Configure doas
  ansible.builtin.template:
    src: doas.conf.j2
    dest: /usr/local/etc/doas.conf
    owner: root
    group: wheel
    mode: '0644'
  when: doas_config is defined

- name: Randomize PIDs
  ansible.posix.sysctl:
    name: kern.randompid
    state: present
    value: "{{ randompid | ternary('1', '0') }}"
    reload: false

- name: Enable coredump
  ansible.posix.sysctl:
    name: kern.coredump
    state: present
    value: "{{ coredump | ternary('1', '0') }}"

- name: Unrestricted debugging
  ansible.posix.sysctl:
    name: security.bsd.unprivileged_proc_debug
    state: present
    value: "{{ unpriv_proc_debug | ternary('1', '0') }}"

- name: Unrestricted message buffer
  ansible.posix.sysctl:
    name: security.bsd.unprivileged_read_msgbuf
    state: present
    value: "{{ unpriv_read_msgbuf | ternary('1', '0') }}"

- name: Show processes running in jails
  ansible.posix.sysctl:
    name: security.bsd.see_jail_proc
    state: present
    value: "{{ see_jail_proc | ternary('1', '0') }}"

- name: Show GIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_gids
    state: present
    value: "{{ see_other_gids | ternary('1', '0') }}"

- name: Show UIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_uids
    state: present
    value: "{{ see_other_uids | ternary('1', '0') }}"

- name: Clear /tmp
  community.general.sysrc:
    name: clear_tmp_enable
    state: present
    value: "{{ clear_tmp | ternary('YES', 'NO') }}"

- name: Enable microcode updates
  community.general.sysrc:
    name: microcode_update_enable
    state: present
    value: "YES"
  notify:
    - Update CPU firmware
  when: microcode_update

- name: Enable ntpd
  community.general.sysrc:
    name: ntpd_enable
    state: present
    value: "{{ ntpd | ternary('YES', 'NO') }}"

- name: Sync ntpd on start
  community.general.sysrc:
    name: ntpd_sync_on_start
    state: present
    value: "{{ ntpd_bootsync | ternary('YES', 'NO') }}"

- name: Enable ntpd OOM protection
  community.general.sysrc:
    name: ntpd_oomprotect
    state: present
    value: "{{ ntpd_oomprotect | ternary('YES', 'NO') }}"

- name: Enable sendmail | incoming
  community.general.sysrc:
    name: sendmail_enable
    state: present
    value: "{{ sendmail | ternary('YES', 'NO') }}"

- name: Enable sendmail | submit
  community.general.sysrc:
    name: sendmail_submit_enable
    state: present
    value: "{{ sendmail_submit | ternary('YES', 'NO') }}"

- name: Enable sendmail | outbound
  community.general.sysrc:
    name: sendmail_outbound_enable
    state: present
    value: "{{ sendmail_outbound | ternary('YES', 'NO') }}"

- name: Enable sendmail | msp_queue
  community.general.sysrc:
    name: sendmail_msp_queue_enable
    state: present
    value: "{{ sendmail_msp_queue | ternary('YES', 'NO') }}"

- name: Set autoboot delay
  community.general.sysrc:
    name: autoboot_delay
    state: present
    value: "2"
    path: /boot/loader.conf

- name: Boot in verbose mode
  community.general.sysrc:
    name: boot_verbose
    state: present
    value: "{{ boot_verbose | ternary('YES', 'NO') }}"
    path: /boot/loader.conf

- name: Change loader logo
  community.general.sysrc:
    name: loader_logo
    state: present
    value: "{{ loader_logo }}"
    path: /boot/loader.conf

- name: Enable AIO
  community.general.sysrc:
    name: aio_load
    state: present
    value: "{{ aio | ternary('YES', 'NO') }}"
    path: /boot/loader.conf

- name: Enable coretemp
  community.general.sysrc:
    name: coretemp_load
    state: present
    value: "{{ coretemp | ternary('YES', 'NO') }}"
    path: /boot/loader.conf

- name: Enable cpuctl
  community.general.sysrc:
    name: cpuctl_load
    state: present
    value: "{{ cpuctl | ternary('YES', 'NO') }}"
    path: /boot/loader.conf

- name: Enable AES-NI
  community.general.sysrc:
    name: aesni_load
    state: present
    value: "{{ aesni | ternary('YES', 'NO') }}"
    path: /boot/loader.conf

- name: Enable H-TCP
  community.general.sysrc:
    name: cc_htcp_load
    state: present
    value: "{{ cc_htcp | ternary('YES', 'NO') }}"
    path: /boot/loader.conf

- name: Enable ping
  community.general.sysrc:
    name: icmp_bmcastecho
    state: present
    value: "{{ bmcastecho | ternary('YES', 'NO') }}"

- name: Load DHCP client in the background
  community.general.sysrc:
    name: background_dhclient
    state: present
    value: "{{ dhclient_bg | ternary('YES', 'NO') }}"

- name: "IPv6 | {{ ipv6_support | ternary('enable', 'disable') }}"
  community.general.sysrc:
    name: rtsold_enable
    state: present
    value: "{{ ipv6_support | ternary('YES', 'NO') }}"

- name: IPv6 | tune
  community.general.sysrc:
    name: rtsold_flags
    state: present
    value: "-aF"
  when: ipv6_support

- name: Tune syslogd
  community.general.sysrc:
    name: syslogd_flags
    state: present
    value: "{{ syslogd_flags }}"

- name: Enable kernel crash dumps
  community.general.sysrc:
    name: dumpdev
    state: present
    value: "{{ dumpdev | ternary('YES', 'NO') }}"

- name: Fix file permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: wheel
    mode: "{{ item.mode }}"
  loop:
    - {path: /etc/cron.d, mode: '0700'}
    - {path: /etc/crontab, mode: '0600'}
    - {path: /etc/ssh/sshd_config, mode: '0600'}
