---

argument_specs:
  main:
    short_description: pf manager
    description:
      - Deploy C(pf) configurations.

    author:
      - charlesrocket

    options:
      bastille:
        description: Deploy C(pf) configuration for C(bastille).
        type: bool
        required: true
