---
- name: Redownload repository catalogue
  ansible.builtin.command: pkg update -f

- name: Upgrade packages
  community.general.pkgng:
    name: "*"
    state: latest

- name: Audit packages
  ansible.builtin.command: pkg audit -F
  register: audit
  failed_when:
    - '"cannot fetch vulnxml" not in audit.stdout'
