---

galaxy_info:
  author: charlesrocket
  description: Manage WiFi
  role_name: wifi
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - wifi
