---

galaxy_info:
  author: charlesrocket
  description: Manage Intel drivers
  role_name: intel
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - intel
