---

- name: Edit user
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh
    groups: dialer,operator,video
    append: yes
  become: True

- name: Upgrade installed packages
  community.general.pkgng:
    name: "*"
    state: latest
  become: True
  when: upgrade_packages

- name: Prepare ports directory
  file:
    path: /usr/ports
    state: directory
    owner: root
    group: wheel
    mode: 0755
  become: True
  when: git_ports
  
- name: Scan ports directory
  find:
    path: /usr/ports
    file_type: any
    hidden: yes
  register: ports_list
  when: git_ports

- name: Clean ports directory
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ ports_list.files }}"
  loop_control:
    label: "{{ item.path }}"
  become: True
  when: git_ports

- name: Install ports
  git:
    repo: 'https://git.freebsd.org/ports.git'
    dest: /usr/ports
    version: main
  become: True
  when: git_ports

- name: Copy MOTD
  copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0755
  become: True

- name: Install MOTD
  cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: True

- name: Edit sh prompt
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.shrc
    line: 'export PS1="\u@\H x: "'
    state: present

- name: Install ohmyzsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"

- name: Ensure mc directory exists
  file:
    path: ~/.config/mc
    state: directory
    mode: 0744

- name: Copy mc config file
  copy:
    src: mcini
    dest: ~/.config/mc/ini
    owner: "{{ ansible_user_id }}"
    mode: 0744
    force: yes

- name: Copy zsh config
  copy:
    src: zshrc
    dest: ~/.zshrc
    owner: "{{ ansible_user_id }}"
    mode: 0644
    force: yes
