---
- name: Edit user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh
    groups: cups,dialer,network,operator,realtime,video,wheel
    append: true
  become: true

- name: Upgrade installed packages
  community.general.pkgng:
    name: "*"
    state: latest
  become: true
  when: upgrade_packages
  notify:
    - Cleanup

- name: Copy MOTD
  ansible.builtin.copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0700
  become: true

- name: Install MOTD
  ansible.builtin.cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: true

- name: Configure make
  ansible.builtin.template:
    src: make.conf.j2
    dest: /etc/make.conf
    owner: root
    group: wheel
    mode: 0644
  become: true

- name: Copy Lynis profile
  ansible.builtin.copy:
    src: desktop.prf
    dest: /usr/local/etc/lynis/desktop.prf
    owner: root
    mode: 0644
  become: true

- name: Install ohmyzsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"

- name: Create home directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
    state: directory
  loop:
    - ~/bin
    - ~/pictures
