---
- name: Edit user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh
    groups: dialer,operator,video
    append: true
  become: true

- name: Upgrade installed packages
  community.general.pkgng:
    name: "*"
    state: latest
  become: true
  when: upgrade_packages

- name: Turn off pulseaudio
  ansible.builtin.lineinfile:
    path: /usr/local/etc/pulse/client.conf
    regexp: '; autospawn = yes'
    line: 'autospawn = no'
    state: present
  become: true
  when: "'pulseaudio' in ansible_facts.packages"

- name: Copy MOTD
  ansible.builtin.copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0755
  become: true

- name: Install MOTD
  ansible.builtin.cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: true

- name: Edit sh prompt
  ansible.builtin.lineinfile:
    dest: /home/{{ ansible_user_id }}/.shrc
    line: 'export PS1="\u@\H x: "'
    state: present

- name: Install ohmyzsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"

- name: Create home directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
    state: directory
  loop:
    - ~/bin
    - ~/pictures
