---

- name: Enable UHD driver
  community.general.sysrc:
    name: kld_list
    value: "i915kms"
    state: present
  become: True

- name: Enable seatd
  community.general.sysrc:
    name: seatd_enable
    value: "YES"
    state: present
  become: True

- name: Edit user
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh
    groups: video
    append: yes
  become: True

- name: Upgrade installed packages
  pkgng:
    name: "*"
    state: latest
  become: True

- name: Copy MOTD
  copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0755
  become: True

- name: Install MOTD
  cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: True

- name: Edit shell prompt
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.shrc
    line: 'export PS1="\u@\H x: "'
    state: present

- name: Install ohmyzsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"
  register: ohmyzsh

- name: Copy .zshrc
  copy:
    src: zshrc
    dest: ~/.zshrc
    owner: "{{ ansible_user_id }}"
    mode: 0644
    force: yes

- name: Copy .alacritty.yml
  copy:
    src: alacritty.yml
    dest: ~/.alacritty.yml
    owner: "{{ ansible_user_id }}"
    mode: 0644
    force: yes
