---

- name: Edit user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh
    groups: "{{ user_groups }}"
    append: true
  when:
    - user_groups is defined
  become: true

- name: Copy MOTD
  ansible.builtin.copy:
    src: >-
      {{ (ansible_play_name == 'FreeBSD Server')
      | ternary('motd-server', 'motd') }}.sh
    dest: /etc/motd.sh
    owner: root
    mode: '0700'
    remote_src: false
  become: true

- name: Install MOTD
  ansible.builtin.cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: true

- name: Configure make
  ansible.builtin.template:
    src: make.conf.j2
    dest: /etc/make.conf
    owner: root
    group: wheel
    mode: '0644'
  become: true
  when:
    - make_config is defined

- name: Copy Lynis profile
  ansible.builtin.copy:
    src: >-
      {{ (ansible_play_name == 'FreeBSD Station')
      | ternary('desktop', 'server') }}.prf
    dest: /usr/local/etc/lynis/custom.prf
    owner: root
    mode: '0644'
    remote_src: false
  become: true
