---

- name: ensure config directory exists
  file:
    path: ~/.config/sway
    state: directory
    mode: '0744'

- name: copy conky config file
  copy:
    src: conkyrc
    dest: ~/.conkyrc
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0744'
    force: yes

- name: copy sway config file
  copy:
    src: swayconfig
    dest: ~/.config/sway/config
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0744'
    force: yes

- name: copy sway-bar script
  copy:
    src: swaybar.sh
    dest: ~/.config/sway/swaybar.sh
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0744'
