---

- name: Check ports directory status
  ansible.builtin.stat:
    path: /usr/ports/.git
  register: ports_status

- name: Prepare ports directory
  ansible.builtin.file:
    path: /usr/ports
    state: directory
    owner: root
    group: wheel
    mode: '0755'
  become: true
  when: ports_status.stat.exists is false

- name: Scan ports directory
  ansible.builtin.find:
    path: /usr/ports
    file_type: any
    hidden: true
  register: ports_list
  when: ports_status.stat.exists is false

- name: Clean ports directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ ports_list.files }}"
  loop_control:
    label: "{{ item.path }}"
  become: true
  when: ports_status.stat.exists is false

- name: Install ports
  ansible.builtin.git:
    repo: 'https://git.freebsd.org/ports.git'
    dest: /usr/ports
    version: main
  become: true
  when: ports_status.stat.exists is false
