---

argument_specs:
  main:
    short_description: Manages packages
    description:
      - Install and upgrade packages.

    author:
      - charlesrocket

    options:
      pkgng_packages:
        description: List of packages to manage.
        type: list
        elements: str
        required: true
