---

galaxy_info:
  author: charlesrocket
  description: Package manager
  role_name: pkg
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - pkg
