---

- name: FreeBSD Server
  hosts: "{{ target | default('all') }}"

  pre_tasks:
    - name: "Activating profile | {{ profile }}"
      charlesrocket.essential.remote_vars:
        url:
          "https://raw.githubusercontent.com/charlesrocket/\
          freebsd-collection/trunk/profiles/{{ profile }}/server.yml"
      tags: ['always']
      when: profile is defined

  roles:
    - role: pkg
      become: true

    - role: sys
      become: true

    - role: mainframe
      become: true

    - role: kern_sec
      when: set_security_level
      become: true

    - role: pf
      when: bastille or pf
      become: true

    - role: wg
      become: true

    - role: common

    - role: charlesrocket.essential.git
      when: (git or poudriere) or git_helper is defined

    - role: charlesrocket.essential.dotfiles
      when: dotfiles_files is defined

    - role: accounting
      when: proc_accounting
      become: true

    - role: bastille
      when: bastille
      become: true

    - role: poudriere
      when: poudriere
      become: true

  post_tasks:
    - name: Upgrade installed packages
      community.general.pkgng:
        name: "*"
        state: latest
        autoremove: true
        cached: false
      become: true
      when: upgrade_packages
