---

- name: FreeBSD Server
  hosts: "{{ target | default('all') }}"

  pre_tasks:
    - name: "Preparing profile | {{ profile }}"
      ansible.builtin.tempfile:
        state: file
        prefix: temp
      register: user_profile
      changed_when: false
      tags: ['always']
      delegate_to: 127.0.0.1
      when: profile is defined

    - name: Downloading profile
      ansible.builtin.uri:
        url:
          "https://raw.githubusercontent.com/charlesrocket/\
          freebsd-collection/trunk/profiles/{{ profile }}/server.yml"
        dest: "{{ user_profile.path }}"
        mode: '0400'
      tags: ['always']
      changed_when: false
      delegate_to: 127.0.0.1
      when: profile is defined

    - name: Activating profile
      ansible.builtin.include_vars:
        file: "{{ user_profile.path }}"
      tags: ['always']
      when: profile is defined

  roles:
    - role: pkg
      become: true

    - role: sys
      become: true

    - role: mainframe
      become: true

    - role: kern_sec
      when: set_security_level
      become: true

    - role: pf
      when: bastille or pf
      become: true

    - role: common

    - role: charlesrocket.essential.git
      when: (git or poudriere) or git_helper is defined

    - role: charlesrocket.essential.dotfiles
      when: dotfiles_files is defined

    - role: accounting
      when: proc_accounting
      become: true

    - role: bastille
      when: bastille
      become: true

    - role: poudriere
      when: poudriere
      become: true

  post_tasks:
    - name: Upgrade installed packages
      community.general.pkgng:
        name: "*"
        state: latest
        autoremove: true
        cached: false
      become: true
      when: upgrade_packages
