---

- name: FreeBSD Station
  hosts: "{{ target | default('all') }}"

  pre_tasks:
    - name: "Activating profile | {{ profile }}"
      charlesrocket.essential.remote_vars:
        url:
          "https://raw.githubusercontent.com/charlesrocket/\
          freebsd-collection/trunk/profiles/{{ profile }}/\
          {{ profile_version | default('station') }}.yml"
      when: profile is defined

  roles:
    - role: pkg
      become: true

    - role: sys
      become: true

    - role: pf
      become: true

    - role: wg
      become: true

    - role: wifi
      become: true
      when: wifi

    - role: kern_sec
      when: security_level is defined
      become: true

    - role: common

    - role: desktop
      become: true

    - role: laptop
      become: true
      when: laptop

    - role: charlesrocket.essential.git

    - role: charlesrocket.essential.dotfiles
      when: dotfiles_files is defined

    - role: git_ports
      when: git_ports

    - role: git_src
      when: git_src

    - role: git_doc
      when: git_doc

    - role: asus
      when: asus

    - role: amd
      when: amd

    - role: clamav
      when: clamav
      become: true

    - role: bastille
      when: bastille
      become: true

    - role: emacs
      when: doomemacs

    - role: intel
      when: intel

    - role: qmk
      when: qmk

    - role: virtualbox
      when: virtualbox
      become: true

  post_tasks:
    - name: Update pkg branch
      ansible.builtin.include_role:
        name: pkg_branch
        apply:
          become: true
