---

- name: FreeBSD Station
  hosts: "{{ target | default('all') }}"

  pre_tasks:
    - name: Load profile
      ansible.builtin.include_vars:
        file: "{{ profile }}/station.yml"
      tags: ['always']
      when: profile is defined

  roles:
    - role: pkg
      become: true

    - role: sys
      become: true

    - role: pf
      become: true

    - role: wifi
      become: true
      when: wifi

    - role: common

    - role: desktop
      become: true

    - role: laptop
      become: true
      when: laptop

    - role: charlesrocket.essential.git

    - role: charlesrocket.essential.dotfiles

    - role: git_ports
      when: git_ports

    - role: git_src
      when: git_src

    - role: git_doc
      when: git_doc

    - role: asus
      when: asus

    - role: amd
      when: amd

    - role: bastille
      when: bastille
      become: true

    - role: emacs
      when: doomemacs

    - role: intel
      when: intel

    - role: qmk
      when: qmk

    - role: virtualbox
      when: virtualbox
      become: true

  post_tasks:
    - name: Update pkg branch
      ansible.builtin.include_role:
        name: pkg_branch
        apply:
          become: true
