---

- name: FreeBSD Station
  hosts: "{{ target | default('all') }}"

  pre_tasks:
    - name: "Preparing profile | {{ profile }}"
      ansible.builtin.tempfile:
        state: file
        prefix: temp
      register: user_profile
      changed_when: false
      tags: ['always']
      delegate_to: 127.0.0.1
      when: profile is defined

    - name: Downloading profile
      ansible.builtin.uri:
        url:
          "https://raw.githubusercontent.com/charlesrocket/\
          freebsd-collection/trunk/profiles/{{ profile }}/station.yml"
        dest: "{{ user_profile.path }}"
        mode: '0400'
      tags: ['always']
      changed_when: false
      delegate_to: 127.0.0.1
      when: profile is defined

    - name: Activating profile
      ansible.builtin.include_vars:
        file: "{{ user_profile.path }}"
      tags: ['always']
      when: profile is defined

  roles:
    - role: pkg
      become: true

    - role: sys
      become: true

    - role: pf
      become: true

    - role: wifi
      become: true
      when: wifi

    - role: common

    - role: desktop
      become: true

    - role: laptop
      become: true
      when: laptop

    - role: charlesrocket.essential.git

    - role: charlesrocket.essential.dotfiles

    - role: git_ports
      when: git_ports

    - role: git_src
      when: git_src

    - role: git_doc
      when: git_doc

    - role: asus
      when: asus

    - role: amd
      when: amd

    - role: bastille
      when: bastille
      become: true

    - role: emacs
      when: doomemacs

    - role: intel
      when: intel

    - role: qmk
      when: qmk

    - role: virtualbox
      when: virtualbox
      become: true

  post_tasks:
    - name: Update pkg branch
      ansible.builtin.include_role:
        name: pkg_branch
        apply:
          become: true
