---

argument_specs:
  main:
    short_description: Installs QMK
    description:
      - Deploy QMK source and tools.

    author:
      - charlesrocket

    options:
      qmk_userspace:
        description: Userspace repository.
        type: str
        default: https://github.com/qmk/qmk_userspace

      qmk_userspace_version:
        description: Userspace repository branch.
        type: str
        default: main

      qmk_userspace_location:
        description: Local userspace destination.
        type: str
        default: ~/src/qmk_userspace

      qmk_firmware:
        description: Firmware repository.
        type: str
        default: https://github.com/qmk/qmk_firmware

      qmk_firmware_version:
        description: Firmware repository branch.
        type: str
        default: master

      qmk_firmware_location:
        description: Local firmware destination.
        type: str
        default: ~/qmk_firmware
